# Generated by Django 4.2.5 on 2023-10-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_project_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline_date',
            field=models.DateField(blank=True, null=True, verbose_name='Крайний срока'),
        ),
    ]
